# SearXNG settings

use_default_settings: false

general:
  debug: false
  instance_name: "SearXNG"

search: 
  safe_search: 0 
  autocomplete: "" 
  autocomplete_min: 4 
  favicon_resolver: "duckduckgo" 
  default_lang: "auto" 
  ban_time_on_fail: 5 
  max_ban_time_on_fail: 120 
  suspended_times: 
    SearxEngineAccessDenied: 86400 
    SearxEngineCaptcha: 86400 
    SearxEngineTooManyRequests: 3600 
    cf_SearxEngineCaptcha: 1296000 
    cf_SearxEngineAccessDenied: 86400 
    recaptcha_SearxEngineCaptcha: 604800 
formats: 
  - html 
  - json

server:
    base_url: http://127.0.0.1  # change this!
    port: 8082
    bind_address: "0.0.0.0"
    secret_key: "309730"           # change this!
    limiter: false
    public_instance: false
    image_proxy: false
    default_http_headers:
      X-Content-Type-Options : nosniff
      X-Download-Options : noopen
      X-Robots-Tag : noindex, nofollow
      Referrer-Policy : no-referrer

redis:
  # URL to connect redis database. Is overwritten by ${SEARXNG_REDIS_URL}.
  url: redis://localhost:6379/1

ui:
  static_use_hash: false
  default_locale: "zh_cn"
  query_in_title: false
  infinite_scroll: false
  center_alignment: false
  cache_url: https://neko.rdfzsz.eu.org/nekoneko/https://web.archive.org/web/
  default_theme: simple
  theme_args:
    simple_style: auto
  search_on_category_select: true
  hotkeys: default
  url_formatting: pretty
  
outgoing: 
  request_timeout: 3.0 
  max_request_timeout: 10.0 
  useragent_suffix: "" 
  pool_connections: 100 
  pool_maxsize: 20 
  enable_http2: true
# preferences:
#   lock:
#     - autocomplete
#     - method

enabled_plugins:
  - 'Basic Calculator'
  - 'Hash plugin'
  - 'Self Information'
  - 'Tracker URL remover'
  - 'Ahmia blacklist'
  # - 'Hostnames plugin'  # see 'hostnames' configuration below
  # - 'Open Access DOI rewrite'

# plugins:
#   - only_show_green_results

# hostnames:
#   replace:
#     '(.*\.)?youtube\.com$': 'invidious.example.com'
#     '(.*\.)?youtu\.be$': 'invidious.example.com'
#   remove:
#     - '(.*\.)?facebook.com$'
#   low_priority:
#     - '(.*\.)?google\.com$'
#   high_priority:
#     - '(.*\.)?wikipedia.org$'

engines:
  - name: arch linux wiki 
    tokens: ['$ecretValue'] 
  - name: bing
    engines: bing 
    disabled: false
  - name: duckduckgo
  - name: bing image
  - name: bilibili
